; ==============================================================================
; TON - Gerado pelo NexOn IoT
; ESP32-S3-WROOM-1-N8R2
; ==============================================================================

[env:ton]
platform = espressif32
board = lolin_s3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.use_1200bps_touch = true
board_upload.wait_for_upload_port = true
board_build.arduino.memory_type = qio_qspi

; Particionamento com 2 slots OTA (app0/app1) + SPIFFS
; Necessario para que Update.h possa gravar em partition nao-ativa
board_build.partitions = default_8MB.csv

lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
    adafruit/Adafruit BusIO@^1.16.1
    knolleary/PubSubClient@^2.8
    4-20ma/ModbusMaster@^2.0.1
    bblanchon/ArduinoJson@^7
    arduino-libraries/Ethernet@^2.0.2

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM=0
    -DCONFIG_SPIRAM_MODE_OCT=0
    -DARDUINO_USB_CDC_ON_BOOT=1
